.code
	PUSH 80			contract Storage {\n\n    uint...
	PUSH 40			contract Storage {\n\n    uint...
	MSTORE 			contract Storage {\n\n    uint...
	CALLVALUE 			contract Storage {\n\n    uint...
	DUP1 			contract Storage {\n\n    uint...
	ISZERO 			contract Storage {\n\n    uint...
	PUSH [tag] 1			contract Storage {\n\n    uint...
	JUMPI 			contract Storage {\n\n    uint...
	PUSH 0			contract Storage {\n\n    uint...
	DUP1 			contract Storage {\n\n    uint...
	REVERT 			contract Storage {\n\n    uint...
tag 1			contract Storage {\n\n    uint...
	JUMPDEST 			contract Storage {\n\n    uint...
	POP 			contract Storage {\n\n    uint...
	PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract Storage {\n\n    uint...
	DUP1 			contract Storage {\n\n    uint...
	PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract Storage {\n\n    uint...
	PUSH 0			contract Storage {\n\n    uint...
	CODECOPY 			contract Storage {\n\n    uint...
	PUSH 0			contract Storage {\n\n    uint...
	RETURN 			contract Storage {\n\n    uint...
.data
	0:
		.code
			PUSH 80			contract Storage {\n\n    uint...
			PUSH 40			contract Storage {\n\n    uint...
			MSTORE 			contract Storage {\n\n    uint...
			CALLVALUE 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			ISZERO 			contract Storage {\n\n    uint...
			PUSH [tag] 1			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			PUSH 0			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			REVERT 			contract Storage {\n\n    uint...
		tag 1			contract Storage {\n\n    uint...
			JUMPDEST 			contract Storage {\n\n    uint...
			POP 			contract Storage {\n\n    uint...
			PUSH 4			contract Storage {\n\n    uint...
			CALLDATASIZE 			contract Storage {\n\n    uint...
			LT 			contract Storage {\n\n    uint...
			PUSH [tag] 2			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			PUSH 0			contract Storage {\n\n    uint...
			CALLDATALOAD 			contract Storage {\n\n    uint...
			PUSH E0			contract Storage {\n\n    uint...
			SHR 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH 2E64CEC1			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 3			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH 9AE4B7D0			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 4			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH C534BE7A			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 5			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
		tag 2			contract Storage {\n\n    uint...
			JUMPDEST 			contract Storage {\n\n    uint...
			PUSH 0			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			REVERT 			contract Storage {\n\n    uint...
		tag 3			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH [tag] 6			function retrieve() public vie...
			PUSH [tag] 7			function retrieve() public vie...
			JUMP 			function retrieve() public vie...
		tag 6			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH 40			function retrieve() public vie...
			MLOAD 			function retrieve() public vie...
			PUSH [tag] 8			function retrieve() public vie...
			SWAP2 			function retrieve() public vie...
			SWAP1 			function retrieve() public vie...
			PUSH [tag] 9			function retrieve() public vie...
			JUMP 			function retrieve() public vie...
		tag 8			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH 40			function retrieve() public vie...
			MLOAD 			function retrieve() public vie...
			DUP1 			function retrieve() public vie...
			SWAP2 			function retrieve() public vie...
			SUB 			function retrieve() public vie...
			SWAP1 			function retrieve() public vie...
			RETURN 			function retrieve() public vie...
		tag 4			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			PUSH [tag] 10			function storeB(uint256 num) p...
			PUSH 4			function storeB(uint256 num) p...
			DUP1 			function storeB(uint256 num) p...
			CALLDATASIZE 			function storeB(uint256 num) p...
			SUB 			function storeB(uint256 num) p...
			DUP2 			function storeB(uint256 num) p...
			ADD 			function storeB(uint256 num) p...
			SWAP1 			function storeB(uint256 num) p...
			PUSH [tag] 11			function storeB(uint256 num) p...
			SWAP2 			function storeB(uint256 num) p...
			SWAP1 			function storeB(uint256 num) p...
			PUSH [tag] 12			function storeB(uint256 num) p...
			JUMP 			function storeB(uint256 num) p...
		tag 11			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			PUSH [tag] 13			function storeB(uint256 num) p...
			JUMP 			function storeB(uint256 num) p...
		tag 10			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			STOP 			function storeB(uint256 num) p...
		tag 5			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			PUSH [tag] 14			function storeA(uint256 num) p...
			PUSH 4			function storeA(uint256 num) p...
			DUP1 			function storeA(uint256 num) p...
			CALLDATASIZE 			function storeA(uint256 num) p...
			SUB 			function storeA(uint256 num) p...
			DUP2 			function storeA(uint256 num) p...
			ADD 			function storeA(uint256 num) p...
			SWAP1 			function storeA(uint256 num) p...
			PUSH [tag] 15			function storeA(uint256 num) p...
			SWAP2 			function storeA(uint256 num) p...
			SWAP1 			function storeA(uint256 num) p...
			PUSH [tag] 12			function storeA(uint256 num) p...
			JUMP 			function storeA(uint256 num) p...
		tag 15			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			PUSH [tag] 16			function storeA(uint256 num) p...
			JUMP 			function storeA(uint256 num) p...
		tag 14			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			STOP 			function storeA(uint256 num) p...
		tag 7			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH 0			uint256
			PUSH [tag] 18			Multiply( numberA, numberB)
			PUSH 0			numberA
			SLOAD 			numberA
			PUSH 1			numberB
			SLOAD 			numberB
			PUSH [tag] 19			Multiply
			JUMP 			Multiply( numberA, numberB)
		tag 18			Multiply( numberA, numberB)
			JUMPDEST 			Multiply( numberA, numberB)
			SWAP1 			return Multiply( numberA, numb...
			POP 			return Multiply( numberA, numb...
			SWAP1 			function retrieve() public vie...
			JUMP 			function retrieve() public vie...
		tag 13			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			DUP1 			num
			PUSH 1			numberB
			DUP2 			numberB = num
			SWAP1 			numberB = num
			SSTORE 			numberB = num
			POP 			numberB = num
			POP 			function storeB(uint256 num) p...
			JUMP 			function storeB(uint256 num) p...
		tag 16			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			DUP1 			num
			PUSH 0			numberA
			DUP2 			numberA = num
			SWAP1 			numberA = num
			SSTORE 			numberA = num
			POP 			numberA = num
			POP 			function storeA(uint256 num) p...
			JUMP 			function storeA(uint256 num) p...
		tag 19			function Multiply(uint a, uint...
			JUMPDEST 			function Multiply(uint a, uint...
			PUSH 0			uint256
			DUP2 			b
			DUP4 			a
			PUSH [tag] 23			a * b
			SWAP2 			a * b
			SWAP1 			a * b
			PUSH [tag] 24			a * b
			JUMP 			a * b
		tag 23			a * b
			JUMPDEST 			a * b
			SWAP1 			return a * b
			POP 			return a * b
			SWAP3 			function Multiply(uint a, uint...
			SWAP2 			function Multiply(uint a, uint...
			POP 			function Multiply(uint a, uint...
			POP 			function Multiply(uint a, uint...
			JUMP 			function Multiply(uint a, uint...
		tag 25			-License-Identifier: GPL-3.0\n...
			JUMPDEST 			-License-Identifier: GPL-3.0\n...
			PUSH 0			solidit
			DUP2 			le St
			SWAP1 			/**\n * @title St
			POP 			/**\n * @title St
			SWAP2 			-License-Identifier: GPL-3.0\n...
			SWAP1 			-License-Identifier: GPL-3.0\n...
			POP 			-License-Identifier: GPL-3.0\n...
			JUMP 			-License-Identifier: GPL-3.0\n...
		tag 26			v Store & retrieve value in a ...
			JUMPDEST 			v Store & retrieve value in a ...
			PUSH [tag] 36			ethers.ts\n */\ncontract S
			DUP2 			ract 
			PUSH [tag] 25			ethers.ts\n */\ncontract S
			JUMP 			ethers.ts\n */\ncontract S
		tag 36			ethers.ts\n */\ncontract S
			JUMPDEST 			ethers.ts\n */\ncontract S
			DUP3 			wit
			MSTORE 			deploy_with_ethers.ts\n */\nco...
			POP 			v Store & retrieve value in a ...
			POP 			v Store & retrieve value in a ...
			JUMP 			v Store & retrieve value in a ...
		tag 9			 uint256 numberA;\n    uint256...
			JUMPDEST 			 uint256 numberA;\n    uint256...
			PUSH 0			`num
			PUSH 20			to
			DUP3 			 value to
			ADD 			 num value to stor
			SWAP1 			* @param num value to stor
			POP 			* @param num value to stor
			PUSH [tag] 38			    function storeA(uint256 nu...
			PUSH 0			 
			DUP4 			 = num;\n 
			ADD 			berA = num;\n    }
			DUP5 			      
			PUSH [tag] 26			    function storeA(uint256 nu...
			JUMP 			    function storeA(uint256 nu...
		tag 38			    function storeA(uint256 nu...
			JUMPDEST 			    function storeA(uint256 nu...
			SWAP3 			 uint256 numberA;\n    uint256...
			SWAP2 			 uint256 numberA;\n    uint256...
			POP 			 uint256 numberA;\n    uint256...
			POP 			 uint256 numberA;\n    uint256...
			JUMP 			 uint256 numberA;\n    uint256...
		tag 28			@param num value to store\n   ...
			JUMPDEST 			@param num value to store\n   ...
			PUSH 0			/
			DUP1 			 
			REVERT 			    }\n    //
		tag 30			ction retrieve() public view r...
			JUMPDEST 			ction retrieve() public view r...
			PUSH [tag] 43			 numberA, numberB);\n    
			DUP2 			;\n   
			PUSH [tag] 25			 numberA, numberB);\n    
			JUMP 			 numberA, numberB);\n    
		tag 43			 numberA, numberB);\n    
			JUMPDEST 			 numberA, numberB);\n    
			DUP2 			ltipl
			EQ 			 Multiply( numberA, numberB);\...
			PUSH [tag] 44			    return Multiply( numberA, ...
			JUMPI 			    return Multiply( numberA, ...
			PUSH 0			 
			DUP1 			h
			REVERT 			 // hash : 2
		tag 44			    return Multiply( numberA, ...
			JUMPDEST 			    return Multiply( numberA, ...
			POP 			ction retrieve() public view r...
			JUMP 			ction retrieve() public view r...
		tag 31			/**\n     * @dev Return value ...
			JUMPDEST 			/**\n     * @dev Return value ...
			PUSH 0			omput
			DUP2 			 of tw
			CALLDATALOAD 			tiplification of two
			SWAP1 			n the multiplification of two
			POP 			n the multiplification of two
			PUSH [tag] 46			    */\n    function Multiply(...
			DUP2 			y(uin
			PUSH [tag] 30			    */\n    function Multiply(...
			JUMP 			    */\n    function Multiply(...
		tag 46			    */\n    function Multiply(...
			JUMPDEST 			    */\n    function Multiply(...
			SWAP3 			/**\n     * @dev Return value ...
			SWAP2 			/**\n     * @dev Return value ...
			POP 			/**\n     * @dev Return value ...
			POP 			/**\n     * @dev Return value ...
			JUMP 			/**\n     * @dev Return value ...
		tag 12			pure private returns(uint256) ...
			JUMPDEST 			pure private returns(uint256) ...
			PUSH 0			\n    /
			PUSH 20			
			DUP3 			
			DUP5 			
			SUB 			\n}
			SLT 			xxx\n\n}
			ISZERO 			xxxxxx\n\n}
			PUSH [tag] 48			xxxxxx\n\n}
			JUMPI 			xxxxxx\n\n}
			PUSH [tag] 49			
			PUSH [tag] 28			
			JUMP 			
		tag 49			
			JUMPDEST 			
		tag 48			xxxxxx\n\n}
			JUMPDEST 			xxxxxx\n\n}
			PUSH 0			
			PUSH [tag] 50			
			DUP5 			
			DUP3 			
			DUP6 			
			ADD 			
			PUSH [tag] 31			
			JUMP 			
		tag 50			
			JUMPDEST 			
			SWAP2 			
			POP 			
			POP 			
			SWAP3 			pure private returns(uint256) ...
			SWAP2 			pure private returns(uint256) ...
			POP 			pure private returns(uint256) ...
			POP 			pure private returns(uint256) ...
			JUMP 			pure private returns(uint256) ...
		tag 32			
			JUMPDEST 			
			PUSH 4E487B7100000000000000000000000000000000000000000000000000000000			
			PUSH 0			
			MSTORE 			
			PUSH 11			
			PUSH 4			
			MSTORE 			
			PUSH 24			
			PUSH 0			
			REVERT 			
		tag 24			
			JUMPDEST 			
			PUSH 0			
			PUSH [tag] 53			
			DUP3 			
			PUSH [tag] 25			
			JUMP 			
		tag 53			
			JUMPDEST 			
			SWAP2 			
			POP 			
			PUSH [tag] 54			
			DUP4 			
			PUSH [tag] 25			
			JUMP 			
		tag 54			
			JUMPDEST 			
			SWAP3 			
			POP 			
			DUP3 			
			DUP3 			
			MUL 			
			PUSH [tag] 55			
			DUP2 			
			PUSH [tag] 25			
			JUMP 			
		tag 55			
			JUMPDEST 			
			SWAP2 			
			POP 			
			DUP3 			
			DUP3 			
			DIV 			
			DUP5 			
			EQ 			
			DUP4 			
			ISZERO 			
			OR 			
			PUSH [tag] 56			
			JUMPI 			
			PUSH [tag] 57			
			PUSH [tag] 32			
			JUMP 			
		tag 57			
			JUMPDEST 			
		tag 56			
			JUMPDEST 			
			POP 			
			SWAP3 			
			SWAP2 			
			POP 			
			POP 			
			JUMP 			
		.data
