.code
	PUSH 80			contract Storage {\n\n    uint...
	PUSH 40			contract Storage {\n\n    uint...
	MSTORE 			contract Storage {\n\n    uint...
	CALLVALUE 			contract Storage {\n\n    uint...
	DUP1 			contract Storage {\n\n    uint...
	ISZERO 			contract Storage {\n\n    uint...
	PUSH [tag] 1			contract Storage {\n\n    uint...
	JUMPI 			contract Storage {\n\n    uint...
	PUSH 0			contract Storage {\n\n    uint...
	DUP1 			contract Storage {\n\n    uint...
	REVERT 			contract Storage {\n\n    uint...
tag 1			contract Storage {\n\n    uint...
	JUMPDEST 			contract Storage {\n\n    uint...
	POP 			contract Storage {\n\n    uint...
	PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract Storage {\n\n    uint...
	DUP1 			contract Storage {\n\n    uint...
	PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract Storage {\n\n    uint...
	PUSH 0			contract Storage {\n\n    uint...
	CODECOPY 			contract Storage {\n\n    uint...
	PUSH 0			contract Storage {\n\n    uint...
	RETURN 			contract Storage {\n\n    uint...
.data
	0:
		.code
			PUSH 80			contract Storage {\n\n    uint...
			PUSH 40			contract Storage {\n\n    uint...
			MSTORE 			contract Storage {\n\n    uint...
			CALLVALUE 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			ISZERO 			contract Storage {\n\n    uint...
			PUSH [tag] 1			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			PUSH 0			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			REVERT 			contract Storage {\n\n    uint...
		tag 1			contract Storage {\n\n    uint...
			JUMPDEST 			contract Storage {\n\n    uint...
			POP 			contract Storage {\n\n    uint...
			PUSH 4			contract Storage {\n\n    uint...
			CALLDATASIZE 			contract Storage {\n\n    uint...
			LT 			contract Storage {\n\n    uint...
			PUSH [tag] 2			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			PUSH 0			contract Storage {\n\n    uint...
			CALLDATALOAD 			contract Storage {\n\n    uint...
			PUSH E0			contract Storage {\n\n    uint...
			SHR 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH 2E64CEC1			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 3			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH 4CF56E0C			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 4			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH 9AE4B7D0			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 5			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH B87C712B			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 6			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			PUSH C534BE7A			contract Storage {\n\n    uint...
			EQ 			contract Storage {\n\n    uint...
			PUSH [tag] 7			contract Storage {\n\n    uint...
			JUMPI 			contract Storage {\n\n    uint...
		tag 2			contract Storage {\n\n    uint...
			JUMPDEST 			contract Storage {\n\n    uint...
			PUSH 0			contract Storage {\n\n    uint...
			DUP1 			contract Storage {\n\n    uint...
			REVERT 			contract Storage {\n\n    uint...
		tag 3			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH [tag] 8			function retrieve() public vie...
			PUSH [tag] 9			function retrieve() public vie...
			JUMP 			function retrieve() public vie...
		tag 8			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH 40			function retrieve() public vie...
			MLOAD 			function retrieve() public vie...
			PUSH [tag] 10			function retrieve() public vie...
			SWAP2 			function retrieve() public vie...
			SWAP1 			function retrieve() public vie...
			PUSH [tag] 11			function retrieve() public vie...
			JUMP 			function retrieve() public vie...
		tag 10			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH 40			function retrieve() public vie...
			MLOAD 			function retrieve() public vie...
			DUP1 			function retrieve() public vie...
			SWAP2 			function retrieve() public vie...
			SUB 			function retrieve() public vie...
			SWAP1 			function retrieve() public vie...
			RETURN 			function retrieve() public vie...
		tag 4			function storeC(uint256 num) p...
			JUMPDEST 			function storeC(uint256 num) p...
			PUSH [tag] 12			function storeC(uint256 num) p...
			PUSH 4			function storeC(uint256 num) p...
			DUP1 			function storeC(uint256 num) p...
			CALLDATASIZE 			function storeC(uint256 num) p...
			SUB 			function storeC(uint256 num) p...
			DUP2 			function storeC(uint256 num) p...
			ADD 			function storeC(uint256 num) p...
			SWAP1 			function storeC(uint256 num) p...
			PUSH [tag] 13			function storeC(uint256 num) p...
			SWAP2 			function storeC(uint256 num) p...
			SWAP1 			function storeC(uint256 num) p...
			PUSH [tag] 14			function storeC(uint256 num) p...
			JUMP 			function storeC(uint256 num) p...
		tag 13			function storeC(uint256 num) p...
			JUMPDEST 			function storeC(uint256 num) p...
			PUSH [tag] 15			function storeC(uint256 num) p...
			JUMP 			function storeC(uint256 num) p...
		tag 12			function storeC(uint256 num) p...
			JUMPDEST 			function storeC(uint256 num) p...
			STOP 			function storeC(uint256 num) p...
		tag 5			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			PUSH [tag] 16			function storeB(uint256 num) p...
			PUSH 4			function storeB(uint256 num) p...
			DUP1 			function storeB(uint256 num) p...
			CALLDATASIZE 			function storeB(uint256 num) p...
			SUB 			function storeB(uint256 num) p...
			DUP2 			function storeB(uint256 num) p...
			ADD 			function storeB(uint256 num) p...
			SWAP1 			function storeB(uint256 num) p...
			PUSH [tag] 17			function storeB(uint256 num) p...
			SWAP2 			function storeB(uint256 num) p...
			SWAP1 			function storeB(uint256 num) p...
			PUSH [tag] 14			function storeB(uint256 num) p...
			JUMP 			function storeB(uint256 num) p...
		tag 17			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			PUSH [tag] 18			function storeB(uint256 num) p...
			JUMP 			function storeB(uint256 num) p...
		tag 16			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			STOP 			function storeB(uint256 num) p...
		tag 6			function storeD(uint256 num) p...
			JUMPDEST 			function storeD(uint256 num) p...
			PUSH [tag] 19			function storeD(uint256 num) p...
			PUSH 4			function storeD(uint256 num) p...
			DUP1 			function storeD(uint256 num) p...
			CALLDATASIZE 			function storeD(uint256 num) p...
			SUB 			function storeD(uint256 num) p...
			DUP2 			function storeD(uint256 num) p...
			ADD 			function storeD(uint256 num) p...
			SWAP1 			function storeD(uint256 num) p...
			PUSH [tag] 20			function storeD(uint256 num) p...
			SWAP2 			function storeD(uint256 num) p...
			SWAP1 			function storeD(uint256 num) p...
			PUSH [tag] 14			function storeD(uint256 num) p...
			JUMP 			function storeD(uint256 num) p...
		tag 20			function storeD(uint256 num) p...
			JUMPDEST 			function storeD(uint256 num) p...
			PUSH [tag] 21			function storeD(uint256 num) p...
			JUMP 			function storeD(uint256 num) p...
		tag 19			function storeD(uint256 num) p...
			JUMPDEST 			function storeD(uint256 num) p...
			STOP 			function storeD(uint256 num) p...
		tag 7			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			PUSH [tag] 22			function storeA(uint256 num) p...
			PUSH 4			function storeA(uint256 num) p...
			DUP1 			function storeA(uint256 num) p...
			CALLDATASIZE 			function storeA(uint256 num) p...
			SUB 			function storeA(uint256 num) p...
			DUP2 			function storeA(uint256 num) p...
			ADD 			function storeA(uint256 num) p...
			SWAP1 			function storeA(uint256 num) p...
			PUSH [tag] 23			function storeA(uint256 num) p...
			SWAP2 			function storeA(uint256 num) p...
			SWAP1 			function storeA(uint256 num) p...
			PUSH [tag] 14			function storeA(uint256 num) p...
			JUMP 			function storeA(uint256 num) p...
		tag 23			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			PUSH [tag] 24			function storeA(uint256 num) p...
			JUMP 			function storeA(uint256 num) p...
		tag 22			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			STOP 			function storeA(uint256 num) p...
		tag 9			function retrieve() public vie...
			JUMPDEST 			function retrieve() public vie...
			PUSH 0			uint256
			PUSH [tag] 26			Multiply( numberA, numberB, nu...
			PUSH 0			numberA
			SLOAD 			numberA
			PUSH 1			numberB
			SLOAD 			numberB
			PUSH 2			numberC
			SLOAD 			numberC
			PUSH 3			numberD
			SLOAD 			numberD
			PUSH [tag] 27			Multiply
			JUMP 			Multiply( numberA, numberB, nu...
		tag 26			Multiply( numberA, numberB, nu...
			JUMPDEST 			Multiply( numberA, numberB, nu...
			SWAP1 			return Multiply( numberA, numb...
			POP 			return Multiply( numberA, numb...
			SWAP1 			function retrieve() public vie...
			JUMP 			function retrieve() public vie...
		tag 15			function storeC(uint256 num) p...
			JUMPDEST 			function storeC(uint256 num) p...
			DUP1 			num
			PUSH 2			numberC
			DUP2 			numberC = num
			SWAP1 			numberC = num
			SSTORE 			numberC = num
			POP 			numberC = num
			POP 			function storeC(uint256 num) p...
			JUMP 			function storeC(uint256 num) p...
		tag 18			function storeB(uint256 num) p...
			JUMPDEST 			function storeB(uint256 num) p...
			DUP1 			num
			PUSH 1			numberB
			DUP2 			numberB = num
			SWAP1 			numberB = num
			SSTORE 			numberB = num
			POP 			numberB = num
			POP 			function storeB(uint256 num) p...
			JUMP 			function storeB(uint256 num) p...
		tag 21			function storeD(uint256 num) p...
			JUMPDEST 			function storeD(uint256 num) p...
			DUP1 			num
			PUSH 3			numberD
			DUP2 			numberD = num
			SWAP1 			numberD = num
			SSTORE 			numberD = num
			POP 			numberD = num
			POP 			function storeD(uint256 num) p...
			JUMP 			function storeD(uint256 num) p...
		tag 24			function storeA(uint256 num) p...
			JUMPDEST 			function storeA(uint256 num) p...
			DUP1 			num
			PUSH 0			numberA
			DUP2 			numberA = num
			SWAP1 			numberA = num
			SSTORE 			numberA = num
			POP 			numberA = num
			POP 			function storeA(uint256 num) p...
			JUMP 			function storeA(uint256 num) p...
		tag 27			function Multiply(uint a, uint...
			JUMPDEST 			function Multiply(uint a, uint...
			PUSH 0			uint256
			DUP2 			d
			DUP4 			c
			DUP6 			b
			DUP8 			a
			PUSH [tag] 33			a * b
			SWAP2 			a * b
			SWAP1 			a * b
			PUSH [tag] 34			a * b
			JUMP 			a * b
		tag 33			a * b
			JUMPDEST 			a * b
			PUSH [tag] 35			a * b * c
			SWAP2 			a * b * c
			SWAP1 			a * b * c
			PUSH [tag] 34			a * b * c
			JUMP 			a * b * c
		tag 35			a * b * c
			JUMPDEST 			a * b * c
			PUSH [tag] 36			a * b * c * d
			SWAP2 			a * b * c * d
			SWAP1 			a * b * c * d
			PUSH [tag] 34			a * b * c * d
			JUMP 			a * b * c * d
		tag 36			a * b * c * d
			JUMPDEST 			a * b * c * d
			SWAP1 			return a * b * c * d
			POP 			return a * b * c * d
			SWAP5 			function Multiply(uint a, uint...
			SWAP4 			function Multiply(uint a, uint...
			POP 			function Multiply(uint a, uint...
			POP 			function Multiply(uint a, uint...
			POP 			function Multiply(uint a, uint...
			POP 			function Multiply(uint a, uint...
			JUMP 			function Multiply(uint a, uint...
		tag 37			-License-Identifier: GPL-3.0\n...
			JUMPDEST 			-License-Identifier: GPL-3.0\n...
			PUSH 0			solidit
			DUP2 			le St
			SWAP1 			/**\n * @title St
			POP 			/**\n * @title St
			SWAP2 			-License-Identifier: GPL-3.0\n...
			SWAP1 			-License-Identifier: GPL-3.0\n...
			POP 			-License-Identifier: GPL-3.0\n...
			JUMP 			-License-Identifier: GPL-3.0\n...
		tag 38			v Store & retrieve value in a ...
			JUMPDEST 			v Store & retrieve value in a ...
			PUSH [tag] 48			ethers.ts\n */\ncontract S
			DUP2 			ract 
			PUSH [tag] 37			ethers.ts\n */\ncontract S
			JUMP 			ethers.ts\n */\ncontract S
		tag 48			ethers.ts\n */\ncontract S
			JUMPDEST 			ethers.ts\n */\ncontract S
			DUP3 			wit
			MSTORE 			deploy_with_ethers.ts\n */\nco...
			POP 			v Store & retrieve value in a ...
			POP 			v Store & retrieve value in a ...
			JUMP 			v Store & retrieve value in a ...
		tag 11			 uint256 numberA;\n    uint256...
			JUMPDEST 			 uint256 numberA;\n    uint256...
			PUSH 0			   *
			PUSH 20			bl
			DUP3 			orage var
			ADD 			n storage variable
			SWAP1 			 value in storage variable
			POP 			 value in storage variable
			PUSH [tag] 50			\n     * @param num value to s...
			PUSH 0			6
			DUP4 			oreA(uint
			ADD 			n storeA(uint256 
			DUP5 			  func
			PUSH [tag] 38			\n     * @param num value to s...
			JUMP 			\n     * @param num value to s...
		tag 50			\n     * @param num value to s...
			JUMPDEST 			\n     * @param num value to s...
			SWAP3 			 uint256 numberA;\n    uint256...
			SWAP2 			 uint256 numberA;\n    uint256...
			POP 			 uint256 numberA;\n    uint256...
			POP 			 uint256 numberA;\n    uint256...
			JUMP 			 uint256 numberA;\n    uint256...
		tag 40			alue in storage variable `numb...
			JUMPDEST 			alue in storage variable `numb...
			PUSH 0			p
			DUP1 			m
			REVERT 			t256 num) pu
		tag 42			m num value to store\n     */\...
			JUMPDEST 			m num value to store\n     */\...
			PUSH [tag] 55			      numberC = num;\n   
			DUP2 			m;\n  
			PUSH [tag] 37			      numberC = num;\n   
			JUMP 			      numberC = num;\n   
		tag 55			      numberC = num;\n   
			JUMPDEST 			      numberC = num;\n   
			DUP2 			ic {\n
			EQ 			ublic {\n        numberC = num...
			PUSH [tag] 56			256 num) public {\n        num...
			JUMPI 			256 num) public {\n        num...
			PUSH 0			:
			DUP1 			s
			REVERT 			  // hash : 
		tag 56			256 num) public {\n        num...
			JUMPDEST 			256 num) public {\n        num...
			POP 			m num value to store\n     */\...
			JUMP 			m num value to store\n     */\...
		tag 43			 /**\n     * @dev Store value ...
			JUMPDEST 			 /**\n     * @dev Store value ...
			PUSH 0			le `n
			DUP2 			o stor
			CALLDATALOAD 			m num value to store
			SWAP1 			  * @param num value to store
			POP 			  * @param num value to store
			PUSH [tag] 58			    function storeD(uint256 nu...
			DUP2 			 num)
			PUSH [tag] 42			    function storeD(uint256 nu...
			JUMP 			    function storeD(uint256 nu...
		tag 58			    function storeD(uint256 nu...
			JUMPDEST 			    function storeD(uint256 nu...
			SWAP3 			 /**\n     * @dev Store value ...
			SWAP2 			 /**\n     * @dev Store value ...
			POP 			 /**\n     * @dev Store value ...
			POP 			 /**\n     * @dev Store value ...
			JUMP 			 /**\n     * @dev Store value ...
		tag 14			     numberD = num;\n    }\n  ...
			JUMPDEST 			     numberD = num;\n    }\n  ...
			PUSH 0			    * 
			PUSH 20			mu
			DUP3 			rn value 
			DUP5 			  * @re
			SUB 			\n     * @return value o
			SLT 			lue \n     * @return value of ...
			ISZERO 			 value \n     * @return value ...
			PUSH [tag] 60			 value \n     * @return value ...
			JUMPI 			 value \n     * @return value ...
			PUSH [tag] 61			lification of `numberA` by `nu...
			PUSH [tag] 40			lification of `numberA` by `nu...
			JUMP 			lification of `numberA` by `nu...
		tag 61			lification of `numberA` by `nu...
			JUMPDEST 			lification of `numberA` by `nu...
		tag 60			 value \n     * @return value ...
			JUMPDEST 			 value \n     * @return value ...
			PUSH 0			2
			PUSH [tag] 62			tiply( numberA, numberB, numbe...
			DUP5 			   }\n  
			DUP3 			mberD)
			DUP6 			numberC, 
			ADD 			rB, numberC, numberD);
			PUSH [tag] 43			tiply( numberA, numberB, numbe...
			JUMP 			tiply( numberA, numberB, numbe...
		tag 62			tiply( numberA, numberB, numbe...
			JUMPDEST 			tiply( numberA, numberB, numbe...
			SWAP2 			return Multiply( numberA, numb...
			POP 			return Multiply( numberA, numb...
			POP 			e() public view returns (uint2...
			SWAP3 			     numberD = num;\n    }\n  ...
			SWAP2 			     numberD = num;\n    }\n  ...
			POP 			     numberD = num;\n    }\n  ...
			POP 			     numberD = num;\n    }\n  ...
			JUMP 			     numberD = num;\n    }\n  ...
		tag 44			   /**\n     * @dev Return val...
			JUMPDEST 			   /**\n     * @dev Return val...
			PUSH 4E487B7100000000000000000000000000000000000000000000000000000000			compute and return the multipl...
			PUSH 0			r
			MSTORE 			* @return compute and return t...
			PUSH 11			 b, 
			PUSH 4			i
			MSTORE 			nt a, uint b, u
			PUSH 24			 pri
			PUSH 0			u
			REVERT 			nt d) pure priv
		tag 34			uint256) {\n        return a *...
			JUMPDEST 			uint256) {\n        return a *...
			PUSH 0			\n    }\n
			PUSH [tag] 65			xxxxxx\n\n\n    /**\n   
			DUP3 			 
			PUSH [tag] 37			xxxxxx\n\n\n    /**\n   
			JUMP 			xxxxxx\n\n\n    /**\n   
		tag 65			xxxxxx\n\n\n    /**\n   
			JUMPDEST 			xxxxxx\n\n\n    /**\n   
			SWAP2 			 : xxxxxxxx\n\n\n    /**\n   
			POP 			 : xxxxxxxx\n\n\n    /**\n   
			PUSH [tag] 66			n value \n     * @ret
			DUP4 			e
			PUSH [tag] 37			n value \n     * @ret
			JUMP 			n value \n     * @ret
		tag 66			n value \n     * @ret
			JUMPDEST 			n value \n     * @ret
			SWAP3 			Return value \n     * @ret
			POP 			Return value \n     * @ret
			DUP3 			f
			DUP3 			p
			MUL 			ultiplifi
			PUSH [tag] 67			s\n     */\n    function Multi...
			DUP2 			tion Multip
			PUSH [tag] 37			s\n     */\n    function Multi...
			JUMP 			s\n     */\n    function Multi...
		tag 67			s\n     */\n    function Multi...
			JUMPDEST 			s\n     */\n    function Multi...
			SWAP2 			 four values\n     */\n    fun...
			POP 			 four values\n     */\n    fun...
			DUP3 			
			DUP3 			
			DIV 			
			DUP5 			
			EQ 			
			DUP4 			/
			ISZERO 			}\n    // 
			OR 			 a * b * c * d;\n    }\n    //...
			PUSH [tag] 68			nt256) {\n        return a * b...
			JUMPI 			nt256) {\n        return a * b...
			PUSH [tag] 69			
			PUSH [tag] 44			
			JUMP 			
		tag 69			
			JUMPDEST 			
		tag 68			nt256) {\n        return a * b...
			JUMPDEST 			nt256) {\n        return a * b...
			POP 			   // hash : xxxxxxxx\n\n\n   ...
			SWAP3 			uint256) {\n        return a *...
			SWAP2 			uint256) {\n        return a *...
			POP 			uint256) {\n        return a *...
			POP 			uint256) {\n        return a *...
			JUMP 			uint256) {\n        return a *...
		.data
