.code
  PUSH 80			contract Storage {\n\n    uint...
  PUSH 40			contract Storage {\n\n    uint...
  MSTORE 			contract Storage {\n\n    uint...
  CALLVALUE 			contract Storage {\n\n    uint...
  DUP1 			contract Storage {\n\n    uint...
  ISZERO 			contract Storage {\n\n    uint...
  PUSH [tag] 1			contract Storage {\n\n    uint...
  JUMPI 			contract Storage {\n\n    uint...
  PUSH 0			contract Storage {\n\n    uint...
  DUP1 			contract Storage {\n\n    uint...
  REVERT 			contract Storage {\n\n    uint...
tag 1			contract Storage {\n\n    uint...
  JUMPDEST 			contract Storage {\n\n    uint...
  POP 			contract Storage {\n\n    uint...
  PUSH #[$] 0000000000000000000000000000000000000000000000000000000000000000			contract Storage {\n\n    uint...
  DUP1 			contract Storage {\n\n    uint...
  PUSH [$] 0000000000000000000000000000000000000000000000000000000000000000			contract Storage {\n\n    uint...
  PUSH 0			contract Storage {\n\n    uint...
  CODECOPY 			contract Storage {\n\n    uint...
  PUSH 0			contract Storage {\n\n    uint...
  RETURN 			contract Storage {\n\n    uint...
.data
  0:
	.code
	  PUSH 80			contract Storage {\n\n    uint...
	  PUSH 40			contract Storage {\n\n    uint...
	  MSTORE 			contract Storage {\n\n    uint...
	  CALLVALUE 			contract Storage {\n\n    uint...
	  DUP1 			contract Storage {\n\n    uint...
	  ISZERO 			contract Storage {\n\n    uint...
	  PUSH [tag] 1			contract Storage {\n\n    uint...
	  JUMPI 			contract Storage {\n\n    uint...
	  PUSH 0			contract Storage {\n\n    uint...
	  DUP1 			contract Storage {\n\n    uint...
	  REVERT 			contract Storage {\n\n    uint...
	tag 1			contract Storage {\n\n    uint...
	  JUMPDEST 			contract Storage {\n\n    uint...
	  POP 			contract Storage {\n\n    uint...
	  PUSH 4			contract Storage {\n\n    uint...
	  CALLDATASIZE 			contract Storage {\n\n    uint...
	  LT 			contract Storage {\n\n    uint...
	  PUSH [tag] 2			contract Storage {\n\n    uint...
	  JUMPI 			contract Storage {\n\n    uint...
	  PUSH 0			contract Storage {\n\n    uint...
	  CALLDATALOAD 			contract Storage {\n\n    uint...
	  PUSH E0			contract Storage {\n\n    uint...
	  SHR 			contract Storage {\n\n    uint...
	  DUP1 			contract Storage {\n\n    uint...
	  PUSH 2E64CEC1			contract Storage {\n\n    uint...
	  EQ 			contract Storage {\n\n    uint...
	  PUSH [tag] 3			contract Storage {\n\n    uint...
	  JUMPI 			contract Storage {\n\n    uint...
	  DUP1 			contract Storage {\n\n    uint...
	  PUSH 4CF56E0C			contract Storage {\n\n    uint...
	  EQ 			contract Storage {\n\n    uint...
	  PUSH [tag] 4			contract Storage {\n\n    uint...
	  JUMPI 			contract Storage {\n\n    uint...
	  DUP1 			contract Storage {\n\n    uint...
	  PUSH 9AE4B7D0			contract Storage {\n\n    uint...
	  EQ 			contract Storage {\n\n    uint...
	  PUSH [tag] 5			contract Storage {\n\n    uint...
	  JUMPI 			contract Storage {\n\n    uint...
	  DUP1 			contract Storage {\n\n    uint...
	  PUSH C534BE7A			contract Storage {\n\n    uint...
	  EQ 			contract Storage {\n\n    uint...
	  PUSH [tag] 6			contract Storage {\n\n    uint...
	  JUMPI 			contract Storage {\n\n    uint...
	tag 2			contract Storage {\n\n    uint...
	  JUMPDEST 			contract Storage {\n\n    uint...
	  PUSH 0			contract Storage {\n\n    uint...
	  DUP1 			contract Storage {\n\n    uint...
	  REVERT 			contract Storage {\n\n    uint...
	tag 3			function retrieve() public vie...
	  JUMPDEST 			function retrieve() public vie...
	  PUSH [tag] 7			function retrieve() public vie...
	  PUSH [tag] 8			function retrieve() public vie...
	  JUMP 			function retrieve() public vie...
	tag 7			function retrieve() public vie...
	  JUMPDEST 			function retrieve() public vie...
	  PUSH 40			function retrieve() public vie...
	  MLOAD 			function retrieve() public vie...
	  PUSH [tag] 9			function retrieve() public vie...
	  SWAP2 			function retrieve() public vie...
	  SWAP1 			function retrieve() public vie...
	  PUSH [tag] 10			function retrieve() public vie...
	  JUMP 			function retrieve() public vie...
	tag 9			function retrieve() public vie...
	  JUMPDEST 			function retrieve() public vie...
	  PUSH 40			function retrieve() public vie...
	  MLOAD 			function retrieve() public vie...
	  DUP1 			function retrieve() public vie...
	  SWAP2 			function retrieve() public vie...
	  SUB 			function retrieve() public vie...
	  SWAP1 			function retrieve() public vie...
	  RETURN 			function retrieve() public vie...
	tag 4			function storeC(uint256 num) p...
	  JUMPDEST 			function storeC(uint256 num) p...
	  PUSH [tag] 11			function storeC(uint256 num) p...
	  PUSH 4			function storeC(uint256 num) p...
	  DUP1 			function storeC(uint256 num) p...
	  CALLDATASIZE 			function storeC(uint256 num) p...
	  SUB 			function storeC(uint256 num) p...
	  DUP2 			function storeC(uint256 num) p...
	  ADD 			function storeC(uint256 num) p...
	  SWAP1 			function storeC(uint256 num) p...
	  PUSH [tag] 12			function storeC(uint256 num) p...
	  SWAP2 			function storeC(uint256 num) p...
	  SWAP1 			function storeC(uint256 num) p...
	  PUSH [tag] 13			function storeC(uint256 num) p...
	  JUMP 			function storeC(uint256 num) p...
	tag 12			function storeC(uint256 num) p...
	  JUMPDEST 			function storeC(uint256 num) p...
	  PUSH [tag] 14			function storeC(uint256 num) p...
	  JUMP 			function storeC(uint256 num) p...
	tag 11			function storeC(uint256 num) p...
	  JUMPDEST 			function storeC(uint256 num) p...
	  STOP 			function storeC(uint256 num) p...
	tag 5			function storeB(uint256 num) p...
	  JUMPDEST 			function storeB(uint256 num) p...
	  PUSH [tag] 15			function storeB(uint256 num) p...
	  PUSH 4			function storeB(uint256 num) p...
	  DUP1 			function storeB(uint256 num) p...
	  CALLDATASIZE 			function storeB(uint256 num) p...
	  SUB 			function storeB(uint256 num) p...
	  DUP2 			function storeB(uint256 num) p...
	  ADD 			function storeB(uint256 num) p...
	  SWAP1 			function storeB(uint256 num) p...
	  PUSH [tag] 16			function storeB(uint256 num) p...
	  SWAP2 			function storeB(uint256 num) p...
	  SWAP1 			function storeB(uint256 num) p...
	  PUSH [tag] 13			function storeB(uint256 num) p...
	  JUMP 			function storeB(uint256 num) p...
	tag 16			function storeB(uint256 num) p...
	  JUMPDEST 			function storeB(uint256 num) p...
	  PUSH [tag] 17			function storeB(uint256 num) p...
	  JUMP 			function storeB(uint256 num) p...
	tag 15			function storeB(uint256 num) p...
	  JUMPDEST 			function storeB(uint256 num) p...
	  STOP 			function storeB(uint256 num) p...
	tag 6			function storeA(uint256 num) p...
	  JUMPDEST 			function storeA(uint256 num) p...
	  PUSH [tag] 18			function storeA(uint256 num) p...
	  PUSH 4			function storeA(uint256 num) p...
	  DUP1 			function storeA(uint256 num) p...
	  CALLDATASIZE 			function storeA(uint256 num) p...
	  SUB 			function storeA(uint256 num) p...
	  DUP2 			function storeA(uint256 num) p...
	  ADD 			function storeA(uint256 num) p...
	  SWAP1 			function storeA(uint256 num) p...
	  PUSH [tag] 19			function storeA(uint256 num) p...
	  SWAP2 			function storeA(uint256 num) p...
	  SWAP1 			function storeA(uint256 num) p...
	  PUSH [tag] 13			function storeA(uint256 num) p...
	  JUMP 			function storeA(uint256 num) p...
	tag 19			function storeA(uint256 num) p...
	  JUMPDEST 			function storeA(uint256 num) p...
	  PUSH [tag] 20			function storeA(uint256 num) p...
	  JUMP 			function storeA(uint256 num) p...
	tag 18			function storeA(uint256 num) p...
	  JUMPDEST 			function storeA(uint256 num) p...
	  STOP 			function storeA(uint256 num) p...
	tag 8			function retrieve() public vie...
	  JUMPDEST 			function retrieve() public vie...
	  PUSH 0			uint256
	  PUSH [tag] 22			Multiply( numberA, numberB, nu...
	  PUSH 0			numberA
	  SLOAD 			numberA
	  PUSH 1			numberB
	  SLOAD 			numberB
	  PUSH 2			numberC
	  SLOAD 			numberC
	  PUSH [tag] 23			Multiply
	  JUMP 			Multiply( numberA, numberB, nu...
	tag 22			Multiply( numberA, numberB, nu...
	  JUMPDEST 			Multiply( numberA, numberB, nu...
	  SWAP1 			return Multiply( numberA, numb...
	  POP 			return Multiply( numberA, numb...
	  SWAP1 			function retrieve() public vie...
	  JUMP 			function retrieve() public vie...
	tag 14			function storeC(uint256 num) p...
	  JUMPDEST 			function storeC(uint256 num) p...
	  DUP1 			num
	  PUSH 2			numberC
	  DUP2 			numberC = num
	  SWAP1 			numberC = num
	  SSTORE 			numberC = num
	  POP 			numberC = num
	  POP 			function storeC(uint256 num) p...
	  JUMP 			function storeC(uint256 num) p...
	tag 17			function storeB(uint256 num) p...
	  JUMPDEST 			function storeB(uint256 num) p...
	  DUP1 			num
	  PUSH 1			numberB
	  DUP2 			numberB = num
	  SWAP1 			numberB = num
	  SSTORE 			numberB = num
	  POP 			numberB = num
	  POP 			function storeB(uint256 num) p...
	  JUMP 			function storeB(uint256 num) p...
	tag 20			function storeA(uint256 num) p...
	  JUMPDEST 			function storeA(uint256 num) p...
	  DUP1 			num
	  PUSH 0			numberA
	  DUP2 			numberA = num
	  SWAP1 			numberA = num
	  SSTORE 			numberA = num
	  POP 			numberA = num
	  POP 			function storeA(uint256 num) p...
	  JUMP 			function storeA(uint256 num) p...
	tag 23			function Multiply(uint a, uint...
	  JUMPDEST 			function Multiply(uint a, uint...
	  PUSH 0			uint256
	  DUP2 			c
	  DUP4 			b
	  DUP6 			a
	  PUSH [tag] 28			a * b
	  SWAP2 			a * b
	  SWAP1 			a * b
	  PUSH [tag] 29			a * b
	  JUMP 			a * b
	tag 28			a * b
	  JUMPDEST 			a * b
	  PUSH [tag] 30			a * b * c
	  SWAP2 			a * b * c
	  SWAP1 			a * b * c
	  PUSH [tag] 29			a * b * c
	  JUMP 			a * b * c
	tag 30			a * b * c
	  JUMPDEST 			a * b * c
	  SWAP1 			return a * b * c
	  POP 			return a * b * c
	  SWAP4 			function Multiply(uint a, uint...
	  SWAP3 			function Multiply(uint a, uint...
	  POP 			function Multiply(uint a, uint...
	  POP 			function Multiply(uint a, uint...
	  POP 			function Multiply(uint a, uint...
	  JUMP 			function Multiply(uint a, uint...
	tag 31			-License-Identifier: GPL-3.0\n...
	  JUMPDEST 			-License-Identifier: GPL-3.0\n...
	  PUSH 0			solidit
	  DUP2 			le St
	  SWAP1 			/**\n * @title St
	  POP 			/**\n * @title St
	  SWAP2 			-License-Identifier: GPL-3.0\n...
	  SWAP1 			-License-Identifier: GPL-3.0\n...
	  POP 			-License-Identifier: GPL-3.0\n...
	  JUMP 			-License-Identifier: GPL-3.0\n...
	tag 32			v Store & retrieve value in a ...
	  JUMPDEST 			v Store & retrieve value in a ...
	  PUSH [tag] 42			ethers.ts\n */\ncontract S
	  DUP2 			ract 
	  PUSH [tag] 31			ethers.ts\n */\ncontract S
	  JUMP 			ethers.ts\n */\ncontract S
	tag 42			ethers.ts\n */\ncontract S
	  JUMPDEST 			ethers.ts\n */\ncontract S
	  DUP3 			wit
	  MSTORE 			deploy_with_ethers.ts\n */\nco...
	  POP 			v Store & retrieve value in a ...
	  POP 			v Store & retrieve value in a ...
	  JUMP 			v Store & retrieve value in a ...
	tag 10			 uint256 numberA;\n    uint256...
	  JUMPDEST 			 uint256 numberA;\n    uint256...
	  PUSH 0			 in 
	  PUSH 20			@p
	  DUP3 			rA`\n     
	  ADD 			umberA`\n     * @pa
	  SWAP1 			iable `numberA`\n     * @pa
	  POP 			iable `numberA`\n     * @pa
	  PUSH [tag] 44			lue to store\n     */\n    fun...
	  PUSH 0			 
	  DUP4 			lic {\n   
	  ADD 			 public {\n       
	  DUP5 			t256 n
	  PUSH [tag] 32			lue to store\n     */\n    fun...
	  JUMP 			lue to store\n     */\n    fun...
	tag 44			lue to store\n     */\n    fun...
	  JUMPDEST 			lue to store\n     */\n    fun...
	  SWAP3 			 uint256 numberA;\n    uint256...
	  SWAP2 			 uint256 numberA;\n    uint256...
	  POP 			 uint256 numberA;\n    uint256...
	  POP 			 uint256 numberA;\n    uint256...
	  JUMP 			 uint256 numberA;\n    uint256...
	tag 34			ble `numberB`\n     * @param n...
	  JUMPDEST 			ble `numberB`\n     * @param n...
	  PUSH 0			e
	  DUP1 			u
	  REVERT 			      number
	tag 36			     */\n    function storeC(u...
	  JUMPDEST 			     */\n    function storeC(u...
	  PUSH [tag] 49			    }\n    // hash : 4CF\n
	  DUP2 			: 4CF
	  PUSH [tag] 31			    }\n    // hash : 4CF\n
	  JUMP 			    }\n    // hash : 4CF\n
	tag 49			    }\n    // hash : 4CF\n
	  JUMPDEST 			    }\n    // hash : 4CF\n
	  DUP2 			= num
	  EQ 			rC = num;\n    }\n    // hash ...
	  PUSH [tag] 50			     numberC = num;\n    }\n  ...
	  JUMPI 			     numberC = num;\n    }\n  ...
	  PUSH 0			*
	  DUP1 			 
	  REVERT 			 /**\n     * 
	tag 50			     numberC = num;\n    }\n  ...
	  JUMPDEST 			     numberC = num;\n    }\n  ...
	  POP 			     */\n    function storeC(u...
	  JUMP 			     */\n    function storeC(u...
	tag 37			lue \n     * @return value of ...
	  JUMPDEST 			lue \n     * @return value of ...
	  PUSH 0			of `n
	  DUP2 			\n     
	  CALLDATALOAD 			 by `numberC`\n     *
	  SWAP1 			`numberB` by `numberC`\n     *
	  POP 			`numberB` by `numberC`\n     *
	  PUSH [tag] 52			ction retrieve() public view r...
	  DUP2 			w ret
	  PUSH [tag] 36			ction retrieve() public view r...
	  JUMP 			ction retrieve() public view r...
	tag 52			ction retrieve() public view r...
	  JUMPDEST 			ction retrieve() public view r...
	  SWAP3 			lue \n     * @return value of ...
	  SWAP2 			lue \n     * @return value of ...
	  POP 			lue \n     * @return value of ...
	  POP 			lue \n     * @return value of ...
	  JUMP 			lue \n     * @return value of ...
	tag 13			) {\n        return Multiply( ...
	  JUMPDEST 			) {\n        return Multiply( ...
	  PUSH 0			  }\n  
	  PUSH 20			Re
	  DUP3 			     * @d
	  DUP5 			\n    /*
	  SUB 			C1\n\n\n    /**\n     * @de
	  SLT 			64CEC1\n\n\n    /**\n     * @d...
	  ISZERO 			 2E64CEC1\n\n\n    /**\n     *...
	  PUSH [tag] 54			 2E64CEC1\n\n\n    /**\n     *...
	  JUMPI 			 2E64CEC1\n\n\n    /**\n     *...
	  PUSH [tag] 55			 value \n     * @return comput...
	  PUSH [tag] 34			 value \n     * @return comput...
	  JUMP 			 value \n     * @return comput...
	tag 55			 value \n     * @return comput...
	  JUMPDEST 			 value \n     * @return comput...
	tag 54			 2E64CEC1\n\n\n    /**\n     *...
	  JUMPDEST 			 2E64CEC1\n\n\n    /**\n     *...
	  PUSH 0			t
	  PUSH [tag] 56			 returns(uint256) {\n        r...
	  DUP5 			\n    }\n
	  DUP3 			 * b *
	  DUP6 			   return
	  ADD 			       return a * b * 
	  PUSH [tag] 37			 returns(uint256) {\n        r...
	  JUMP 			 returns(uint256) {\n        r...
	tag 56			 returns(uint256) {\n        r...
	  JUMPDEST 			 returns(uint256) {\n        r...
	  SWAP2 			re private returns(uint256) {\...
	  POP 			re private returns(uint256) {\...
	  POP 			function Multiply(uint a, uint...
	  SWAP3 			) {\n        return Multiply( ...
	  SWAP2 			) {\n        return Multiply( ...
	  POP 			) {\n        return Multiply( ...
	  POP 			) {\n        return Multiply( ...
	  JUMP 			) {\n        return Multiply( ...
	tag 38			}
	  JUMPDEST 			}
	  PUSH 4E487B7100000000000000000000000000000000000000000000000000000000			
	  PUSH 0			
	  MSTORE 			
	  PUSH 11			
	  PUSH 4			
	  MSTORE 			
	  PUSH 24			
	  PUSH 0			
	  REVERT 			
	tag 29			
	  JUMPDEST 			
	  PUSH 0			
	  PUSH [tag] 59			
	  DUP3 			
	  PUSH [tag] 31			
	  JUMP 			
	tag 59			
	  JUMPDEST 			
	  SWAP2 			
	  POP 			
	  PUSH [tag] 60			
	  DUP4 			
	  PUSH [tag] 31			
	  JUMP 			
	tag 60			
	  JUMPDEST 			
	  SWAP3 			
	  POP 			
	  DUP3 			
	  DUP3 			
	  MUL 			
	  PUSH [tag] 61			
	  DUP2 			
	  PUSH [tag] 31			
	  JUMP 			
	tag 61			
	  JUMPDEST 			
	  SWAP2 			
	  POP 			
	  DUP3 			
	  DUP3 			
	  DIV 			
	  DUP5 			
	  EQ 			
	  DUP4 			
	  ISZERO 			
	  OR 			
	  PUSH [tag] 62			
	  JUMPI 			
	  PUSH [tag] 63			
	  PUSH [tag] 38			
	  JUMP 			
	tag 63			
	  JUMPDEST 			
	tag 62			
	  JUMPDEST 			
	  POP 			
	  SWAP3 			
	  SWAP2 			
	  POP 			
	  POP 			
	  JUMP 			
	.data
